### ISSUE TITLE
parenthesis breaking translation from Oracle outer joins to ANSI joins

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#307]
Oracle
<pre>
CREATE OR REPLACE VIEW IDES_PRAHA22.V_NAJUPOMPRE AS
SELECT   MT.ID_NAJUPOMPRE ,MT.ID_NAJUPOMCEL AS ID_NAJUPOMCEL_PK,
           A9.ID_NAJUPOMCEL_A AS ID_NAJUPOMCEL,
           MT.ID_DOBAPLAT ,
           MT.ID_CTYPPRED ,MT.ID_DRUPRE ,MT.ID_POLONAJ ,
           MT.ID_DPLA ,MT.OBDOBI_OD ,MT.OBDOBI_DO,
           MT.STAV_UPOPRE,MT.PLATNOST_OD ,MT.PLATNOST_DO ,
           MT.IDENT ,MT.POZN ,MT.VARSYMBOL ,MT.SPESYMBOL ,
           MT.BLOKOVANO ,MT.ID_DRUPRE_POPLATEK,
           MT.CISLOJEDNAC ,MT.DRUPOPRE ,
           MT.CISLOPOST ,MT.DATVYR ,MT.NAZEV ,
           MT.CVZNIKRADK ,MT.ID_ASPRAVCE ,MT.ID_APROVOZNA,MT.ID_NAJPROS ,
           MT.OBDOBI_OD_SPLT ,MT.OBDOBI_DO_SPLT ,
           A3.KOD_CTYPPRED,
           A3.J1_NAZEV AS TYP_PREDPISU , A4.J1_NAZEV AS DOBA_PLATBY,
           A5.KOD_DPLA,DECODE(MT.ID_DPLA,NULL,'Hotovost',A5.J1_NAZEV ) AS TYP_DRUH_PLATBY ,
           DECODE( MT.ID_DRUPRE , NULL , GET_NAZEV_VYJIMKY_PEN(MT.TYP_ZAZNAMU), A7.J1_NAZEV  ) AS DRUH_PREDPISU,
           A8.J1_NAZEV AS POLONAJ ,
           A9.ANAJMEN AS ANAJMENO ,
           A9.VYP_KDATU AS VYP_KDATU,
           A9A.BYT_NEBYT AS ABYT_NEBYT,
           decode(MT.za_obdobi,NULL,TO_CHAR(MT.OBDOBI_OD,'MM/YYYY'),za_obdobi) AS ZA_OBDOBI1,
          ( FUPRAV_ZA_OBDOBI(decode(MT.za_obdobi,NULL,TO_CHAR(MT.OBDOBI_OD,'MM/YYYY'),za_obdobi))) AS ZA_OBDOBI,
           MT.CASTKAPRED , MT.CASTKAZAPL,
           MT.VYNOSPRED, MT.VYNOSZAPL, MT.VYNOSROZDIL,
           MT.SLUZBYPRED,MT.SLUZBYZAPL, MT.SLUZBYROZDIL,
           DECODE( MT.NEPOCITAT , 'N' , ( MT.CASTKAPRED - MT.CASTKAZAPL ) , 0 ) AS  DLUHPRED,
           MT.ROK,MT.MESIC ,
           MT.ID_CCLE_VLAST,MT.CHYBA, MT.STRP,
           ( SELECT SUM( DECODE(VYPPEN_SKUT,NULL,0,VYPPEN ))
               FROM NAJPENDET B1
               WHERE B1.ID_NAJUPOMPRE = MT.ID_NAJUPOMPRE )   AS VYPPEN_SKUT,
           ( SELECT SUM( NVL(VYPPEN_SKUT_HOD,0 ))
               FROM NAJPENDET B1
               WHERE B1.ID_NAJUPOMPRE = MT.ID_NAJUPOMPRE )   AS VYPPEN_SKUT_HOD,
           ( SELECT SUM( DECODE(PEN_PREDPIS,NULL,0,PEN_PREDPIS ))
               FROM NAJPENDET B1
               WHERE B1.ID_NAJUPOMPRE = MT.ID_NAJUPOMPRE )   AS PEN_PREDPIS ,
           GET_AKTCASTKA_ZAPL_UPOMPRE( MT.ID_NAJUPOMPRE , MT.TYPPOH ) AS EZAPL_AKT,
           MT.PENALE_ZAKON ,MT.ROKPROM ,MT.NEPOCITAT ,
           MT.POCET_ZALOB ,
           DECODE( MT.NEPOCITAT , 'A' , '*' , null ) AS PENALE_NE,
           MT.DATUM_SPLATNOSTI  ,
           MT.ID_NAJVPLAPRE ,
           MT.UCE_DOKLAD ,
           MT.DATUM_ZAPLACENI,
           MT.TYP_ZAZNAMU,
           TRIM(A7.KOD_DRUPRE) AS KOD_DRUPRE ,
           A10.J1_NAZEV AS CNAJPEN,
           A10.KOD_CNAJPEN AS KOD_CNAJPEN ,
           A11.J1_NAZEV AS DRUPRE_POPLATEK,
           MT.NEPOC_PEN,
           DECODE(A12.ID_SSSLOGIN,NULL,MT.IDENT,A12.JMENO)AS LIDENT_JMENO,
           TO_CHAR(MT.DATVYR,'HH24:MI:SS') AS CAS_DATVYR,
           TO_CHAR(MT.DATZMENY,'HH24:MI:SS') AS CAS_DATZMENY,
           A13.JMENO AS LIDENT_ZMENA_JMENO ,
           MT.DATZMENY, MT.DATVYR AS DATVYR1,
           A14.VYNOS_SLUZBY,
           NAJUPOMPRE_CISLO_ZALOBY(MT.ID_NAJUPOMPRE) AS ZALOBCISLO,
           GET_OBDOBI_VYU( 'OBDOOD' , MT.ID_NAJUPOMPRE ,  'ID_NAJUPOMPRE' )
           AS OBDOBI_OD_VYU,
           GET_OBDOBI_VYU( 'OBDODO' , MT.ID_NAJUPOMPRE ,  'ID_NAJUPOMPRE' )
           AS OBDOBI_DO_VYU,
          (select
               NVL(sum(B2.ECASTKA_ODEP),0) from najvupospl B1 ,NAJODPISY B2
               where MT.ID_NAJUPOMPRE=B1.ID_NAJUPOMPRE
               and B1.id_najdatsplt is not null
               AND B2.ID_NAJDATSPLT = B1.ID_NAJDATSPLT
           AND B2.PLATNOST_DO='01.01.4000') as ECASTKA_ODEP,
           0 as POC_ZAZNAM, A9.ID_NAJVZTAH, A15.ID_CCLE,
           A17.PRIJM AS PRIJMENI, A17.JMENO ,
           A17.DAT_NAR, A17.U_DAT,
           (case
             when MT.DATUM_SPLATNOSTI > A17.U_DAT
                 and a17.u_dat is not null and MT.datum_splatnosti is not null
             then 'Po datumu úmrtí'
             when MT.DATUM_SPLATNOSTI < A17.U_DAT
                 and a17.u_dat is not null and MT.datum_splatnosti is not null
             then 'Před datumem narození'
             else 'Po datumu splatnosti'
           end ) AS PRAV_VZNIK ,
           trim(A14.nazev)  as INDEX_NEPL , trim(A18.J1_NAZEV) as METODA_VYP,
           (select MIN(obdobi_od) from najupompre B1
            where B1.ID_NAJUPOMCEL=A14.ID_NAJUPOMCEL) AS NEP_OD,
           (select max(obdobi_do) from najupompre B1
            where B1.ID_NAJUPOMCEL=A14.ID_NAJUPOMCEL) AS NEP_DO,
            trim(A20.KOD_CISPREDVZT) AS KOD_PREDVZT, trim(A20.J1_NAZEV) AS NAZEV_PREDVZT,
            trim(A21.KOD_CISUJEDN) AS KOD_CISUJEDN, trim(A21.J1_NAZEV) AS NAZEV_CISUJEDN,
            trim(A23.KOD_CISUSTRD) AS KOD_CISUSTRD, trim(A23.J1_NAZEV) AS NAZEV_CISUSTRD,
           DECODE(
            (select count(*) from
              najvdatins B1 , najvupospl B2
              where  B1.id_najdatsplt = B2.id_najdatsplt
              and B2.id_najupompre = mt.id_najupompre ),0,
            'N','A') AS JE_ISR,
           A24.J1_NAZEV AS CNAJPEN_2014,
         DECODE( MT.TYPPOH , NULL ,
         (case
           when castkapred=nvl(vynospred,0) and nvl(vynospred,0)<>0 then 'V'
           when castkapred=nvl(sluzbypred,0) and nvl(sluzbypred,0)<>0 then 'S'
           else 'C'
         end ), MT.TYPPOH ) AS TYPPOH,A10.ZKR_PEN,
         MT.SPIS,MT.UPOMINKA,MT.ZAPL_PENALE,MT.BEZDUVODNE_OBOHACENI,
         MT.ID_SPIVDATSPLT,MT.ID_CNAJPEN,MT.RESENO
      FROM NAJUPOMPRE MT , CTYPPRED A3 ,
           CISDOPLA A4 , CISDPLAT A5 ,
           CISDRPRE A7 , CISPOLPRE A8 ,
           NAJUPOMCEL A9, OBPPRSTR A9A,
           CNAJPEN A10 , CISDRPRE A11,
           SSSLOGIN A12, SSSLOGIN A13,
           NAJUPOMCEL A14 ,ssshledej_A A15,
           CLEOSOBY A16, PAROSOBA A17 ,
           CISDRUUPO A18 , NAJVZTAH A19,
           CISPREDVZT A20, CISUJEDN A21,
           UCEVSTRDVZT A22, CISUSTRD A23,
           CNAJPEN A24
       WHERE  MT.ID_CTYPPRED = A3.ID_CTYPPRED(+) AND
              MT.ID_DOBAPLAT = A4.ID_DOBAPLAT(+) AND
              MT.ID_DPLA = A5.ID_DPLA(+) AND
              MT.ID_DRUPRE = A7.ID_DRUPRE(+) AND
              MT.ID_POLONAJ = A8.ID_POLONAJ(+) AND
              MT.ID_NAJUPOMCEL = A9.ID_NAJUPOMCEL AND
              --- REN 09.05.2016 PUVODNE A9.ID_NAJUPOMCEL(+)
              A9.ID_PROSTOR = A9A.ID_PROSTOR(+) AND
              MT.ID_CNAJPEN = A10.ID_CNAJPEN(+) AND
              MT.ID_DRUPRE_POPLATEK = A11.ID_DRUPRE(+) AND
              MT.LIDENT =A12.ID_SSSLOGIN(+) AND
              MT.LIDENT_ZMENA =A13.ID_SSSLOGIN(+) AND
              A9.ID_NAJUPOMCEL_A=A14.ID_NAJUPOMCEL(+) AND
              A9.ID_NAJVZTAH=A15.ID_NAJVZTAH(+) AND
             ( A15.TYP='N' or A15.typ is null ) AND
              A15.ID_CCLE=A16.ID_CCLE(+)AND
              A16.ID_OSOB=A17.ID_OSOB(+) AND
              A14.ID_CISDRUUPO = A18.ID_CISDRUUPO(+) AND
              A9.ID_NAJVZTAH = A19.ID_NAJVZTAH(+) AND
              A19.ID_CISPREDVZT=A20.ID_CISPREDVZT(+) AND
              A19.ID_CISUJEDN = A21.ID_CISUJEDN(+) AND
              A19.ID_NAJVZTAH= A22.ID_NAJVZTAH(+)  AND
              A22.ID_CISUSTRD =A23.ID_CISUSTRD(+) AND
              MT.ID_CNAJPEN_2014 = A24.ID_CNAJPEN(+)
</pre>

Ora2pg:
<pre>
ERROR:  syntax error at or near "AND"
ŘÁDKA 128:         AND ( A15.TYP='N' or A15.typ is null );
                   ^
STATEMENT:  CREATE OR REPLACE VIEW v_najupompre (id_najupompre, id_najupomcel_pk, id_najupomcel, id_dobaplat, id_ctyppred, id_drupre, id_polonaj, id_dpla, obdobi_od, obdobi_do, stav_upopre, platnost_od, platnost_do, ident, pozn, varsymbol, spesymbol, blokovano, id_drupre_poplatek, cislojednac, drupopre, cislopost, datvyr, nazev, cvznikradk, id_aspravce, id_aprovozna, id_najpros, obdobi_od_splt, obdobi_do_splt, kod_ctyppred, typ_predpisu, doba_platby, kod_dpla, typ_druh_platby, druh_predpisu, polonaj, anajme
           A9.ID_NAJUPOMCEL_A AS ID_NAJUPOMCEL,
           MT.ID_DOBAPLAT ,
           MT.ID_CTYPPRED ,MT.ID_DRUPRE ,MT.ID_POLONAJ ,
           MT.ID_DPLA ,MT.OBDOBI_OD ,MT.OBDOBI_DO,
           MT.STAV_UPOPRE,MT.PLATNOST_OD ,MT.PLATNOST_DO ,
           MT.IDENT ,MT.POZN ,MT.VARSYMBOL ,MT.SPESYMBOL ,
           MT.BLOKOVANO ,MT.ID_DRUPRE_POPLATEK,
           MT.CISLOJEDNAC ,MT.DRUPOPRE ,
           MT.CISLOPOST ,MT.DATVYR ,MT.NAZEV ,
           MT.CVZNIKRADK ,MT.ID_ASPRAVCE ,MT.ID_APROVOZNA,MT.ID_NAJPROS ,
           MT.OBDOBI_OD_SPLT ,MT.OBDOBI_DO_SPLT ,
           A3.KOD_CTYPPRED,
           A3.J1_NAZEV AS TYP_PREDPISU , A4.J1_NAZEV AS DOBA_PLATBY,
           A5.KOD_DPLA,CASE WHEN MT.ID_DPLA IS NULL THEN 'Hotovost'  ELSE A5.J1_NAZEV  END TYP_DRUH_PLATBY ,
           DECODE( MT.ID_DRUPRE , NULL , GET_NAZEV_VYJIMKY_PEN(MT.TYP_ZAZNAMU), A7.J1_NAZEV  ) AS DRUH_PREDPISU,
           A8.J1_NAZEV AS POLONAJ ,
           A9.ANAJMEN AS ANAJMENO ,
           A9.VYP_KDATU AS VYP_KDATU,
           A9A.BYT_NEBYT AS ABYT_NEBYT,
           decode(MT.za_obdobi,NULL,TO_CHAR(MT.OBDOBI_OD,'MM/YYYY'),za_obdobi) AS ZA_OBDOBI1,
          ( FUPRAV_ZA_OBDOBI(decode(MT.za_obdobi,NULL,TO_CHAR(MT.OBDOBI_OD,'MM/YYYY'),za_obdobi))) AS ZA_OBDOBI,
           MT.CASTKAPRED , MT.CASTKAZAPL,
           MT.VYNOSPRED, MT.VYNOSZAPL, MT.VYNOSROZDIL,
           MT.SLUZBYPRED,MT.SLUZBYZAPL, MT.SLUZBYROZDIL,
           DECODE( MT.NEPOCITAT , 'N' , ( MT.CASTKAPRED - MT.CASTKAZAPL ) , 0 ) AS  DLUHPRED,
           MT.ROK,MT.MESIC ,
           MT.ID_CCLE_VLAST,MT.CHYBA, MT.STRP,
           ( SELECT SUM( CASE WHEN VYPPEN_SKUT IS NULL THEN 0  ELSE VYPPEN  END )
                FROM NAJPENDET B1
               WHERE B1.ID_NAJUPOMPRE = MT.ID_NAJUPOMPRE )   AS VYPPEN_SKUT,
           ( SELECT SUM( coalesce(VYPPEN_SKUT_HOD,0 ))
               FROM NAJPENDET B1
               WHERE B1.ID_NAJUPOMPRE = MT.ID_NAJUPOMPRE )   AS VYPPEN_SKUT_HOD,
           ( SELECT SUM( CASE WHEN PEN_PREDPIS IS NULL THEN 0  ELSE PEN_PREDPIS  END )
               FROM NAJPENDET B1
               WHERE B1.ID_NAJUPOMPRE = MT.ID_NAJUPOMPRE )   AS PEN_PREDPIS ,
           GET_AKTCASTKA_ZAPL_UPOMPRE( MT.ID_NAJUPOMPRE , MT.TYPPOH ) AS EZAPL_AKT,
           MT.PENALE_ZAKON ,MT.ROKPROM ,MT.NEPOCITAT ,
           MT.POCET_ZALOB ,
           CASE WHEN  MT.NEPOCITAT='A' THEN '*'  ELSE null  END PENALE_NE,
           MT.DATUM_SPLATNOSTI  ,
           MT.ID_NAJVPLAPRE ,
           MT.UCE_DOKLAD ,
           MT.DATUM_ZAPLACENI,
           MT.TYP_ZAZNAMU,
           btrim(A7.KOD_DRUPRE) AS KOD_DRUPRE ,
           A10.J1_NAZEV AS CNAJPEN,
           A10.KOD_CNAJPEN AS KOD_CNAJPEN ,
           A11.J1_NAZEV AS DRUPRE_POPLATEK,
           MT.NEPOC_PEN,
           CASE WHEN A12.ID_SSSLOGIN IS NULL THEN MT.IDENT  ELSE A12.JMENO END LIDENT_JMENO,
           TO_CHAR(MT.DATVYR,'HH24:MI:SS') AS CAS_DATVYR,
           TO_CHAR(MT.DATZMENY,'HH24:MI:SS') AS CAS_DATZMENY,
           A13.JMENO AS LIDENT_ZMENA_JMENO ,
           MT.DATZMENY, MT.DATVYR AS DATVYR1,
           A14.VYNOS_SLUZBY,
           NAJUPOMPRE_CISLO_ZALOBY(MT.ID_NAJUPOMPRE) AS ZALOBCISLO,
           GET_OBDOBI_VYU( 'OBDOOD' , MT.ID_NAJUPOMPRE ,  'ID_NAJUPOMPRE' )
           AS OBDOBI_OD_VYU,
           GET_OBDOBI_VYU( 'OBDODO' , MT.ID_NAJUPOMPRE ,  'ID_NAJUPOMPRE' )
           AS OBDOBI_DO_VYU,
          (select
               coalesce(sum(B2.ECASTKA_ODEP),0) from najvupospl B1 ,NAJODPISY B2
               where MT.ID_NAJUPOMPRE=B1.ID_NAJUPOMPRE
               and B1.id_najdatsplt is not null
               AND B2.ID_NAJDATSPLT = B1.ID_NAJDATSPLT
           AND B2.PLATNOST_DO='01.01.4000') as ECASTKA_ODEP,
           0 as POC_ZAZNAM, A9.ID_NAJVZTAH, A15.ID_CCLE,
           A17.PRIJM AS PRIJMENI, A17.JMENO ,
           A17.DAT_NAR, A17.U_DAT,
           (case
             when MT.DATUM_SPLATNOSTI > A17.U_DAT
                 and a17.u_dat is not null and MT.datum_splatnosti is not null
             then 'Po datumu úmrtí'
             when MT.DATUM_SPLATNOSTI < A17.U_DAT
                 and a17.u_dat is not null and MT.datum_splatnosti is not null
             then 'Před datumem narození'
             else 'Po datumu splatnosti'
           end ) AS PRAV_VZNIK ,
           btrim(A14.nazev)  as INDEX_NEPL , btrim(A18.J1_NAZEV) as METODA_VYP,
           (select MIN(obdobi_od) from najupompre B1
            where B1.ID_NAJUPOMCEL=A14.ID_NAJUPOMCEL) AS NEP_OD,
           (select max(obdobi_do) from najupompre B1
            where B1.ID_NAJUPOMCEL=A14.ID_NAJUPOMCEL) AS NEP_DO,
            btrim(A20.KOD_CISPREDVZT) AS KOD_PREDVZT, btrim(A20.J1_NAZEV) AS NAZEV_PREDVZT,
            btrim(A21.KOD_CISUJEDN) AS KOD_CISUJEDN, btrim(A21.J1_NAZEV) AS NAZEV_CISUJEDN,
            btrim(A23.KOD_CISUSTRD) AS KOD_CISUSTRD, btrim(A23.J1_NAZEV) AS NAZEV_CISUSTRD,
           DECODE(
            (select count(*) from
              najvdatins B1 , najvupospl B2
              where  B1.id_najdatsplt = B2.id_najdatsplt
              and B2.id_najupompre = mt.id_najupompre ),0,
            'N','A') AS JE_ISR,
           A24.J1_NAZEV AS CNAJPEN_2014,
         DECODE( MT.TYPPOH , NULL ,
         (case
           when castkapred=coalesce(vynospred,0) and coalesce(vynospred,0)<>0 then 'V'
           when castkapred=coalesce(sluzbypred,0) and coalesce(sluzbypred,0)<>0 then 'S'
           else 'C'
         end ), MT.TYPPOH ) AS TYPPOH,A10.ZKR_PEN,
         MT.SPIS,MT.UPOMINKA,MT.ZAPL_PENALE,MT.BEZDUVODNE_OBOHACENI,
         MT.ID_SPIVDATSPLT,MT.ID_CNAJPEN,MT.RESENO
      FROM najupompre mt
LEFT OUTER JOIN ctyppred a3 ON (MT.ID_CTYPPRED = A3.ID_CTYPPRED)
LEFT OUTER JOIN cisdopla a4 ON (MT.ID_DOBAPLAT = A4.ID_DOBAPLAT)
LEFT OUTER JOIN cisdplat a5 ON (MT.ID_DPLA = A5.ID_DPLA)
LEFT OUTER JOIN cisdrpre a7 ON (MT.ID_DRUPRE = A7.ID_DRUPRE)
LEFT OUTER JOIN cispolpre a8 ON (MT.ID_POLONAJ = A8.ID_POLONAJ)
LEFT OUTER JOIN cnajpen a10 ON (MT.ID_CNAJPEN = A10.ID_CNAJPEN)
LEFT OUTER JOIN cisdrpre a11 ON (MT.ID_DRUPRE_POPLATEK = A11.ID_DRUPRE)
LEFT OUTER JOIN ssslogin a12 ON (MT.LIDENT = A12.ID_SSSLOGIN)
LEFT OUTER JOIN ssslogin a13 ON (MT.LIDENT_ZMENA = A13.ID_SSSLOGIN)
LEFT OUTER JOIN cnajpen a24 ON (MT.ID_CNAJPEN_2014 = A24.ID_CNAJPEN)
, najupomcel a9
LEFT OUTER JOIN obpprstr a9a ON (A9.ID_PROSTOR = A9A.ID_PROSTOR)
LEFT OUTER JOIN najupomcel a14 ON (A9.ID_NAJUPOMCEL_A = A14.ID_NAJUPOMCEL)
LEFT OUTER JOIN ssshledej_a a15 ON (A9.ID_NAJVZTAH = A15.ID_NAJVZTAH)
LEFT OUTER JOIN najvztah a19 ON (A9.ID_NAJVZTAH = A19.ID_NAJVZTAH)
LEFT OUTER JOIN cisdruupo a18 ON (A14.ID_CISDRUUPO = A18.ID_CISDRUUPO)
LEFT OUTER JOIN cleosoby a16 ON (A15.ID_CCLE = A16.ID_CCLE)
LEFT OUTER JOIN parosoba a17 ON (A16.ID_OSOB = A17.ID_OSOB)
LEFT OUTER JOIN cispredvzt a20 ON (A19.ID_CISPREDVZT = A20.ID_CISPREDVZT)
LEFT OUTER JOIN cisujedn a21 ON (A19.ID_CISUJEDN = A21.ID_CISUJEDN)
LEFT OUTER JOIN ucevstrdvzt a22 ON (A19.ID_NAJVZTAH = A22.ID_NAJVZTAH)
LEFT OUTER JOIN cisustrd a23 ON (A22.ID_CISUSTRD = A23.ID_CISUSTRD)
WHERE MT.ID_NAJUPOMCEL = A9.ID_NAJUPOMCEL AND                
        AND ( A15.TYP='N' or A15.typ is null );
</pre>

**Comment by darold** [comment]
Might be fixed too.

**Comment by okbob** [comment]
It is not fixed.

**Comment by darold** [comment]
Please override your Ora2Pg installation with current devel code, this has been fixed and I can't reproduce the issue. Actual code remove all comment and line 677 of lib/Ora2Pg/PLSQL.pm remove all doubled AND.
I will work on restoring comment later.

**Comment by okbob** [comment]
I don't understand what can be wrong - all ora2pg files removed, starte with fresh cloned repository and still I see the comment:
<pre>
CREATE OR REPLACE VIEW v_najupompre (id_najupompre, id_najupomcel_pk, id_najupomcel, id_dobaplat, id_ctyppred, id_drupre, id_polonaj, id_dpla, obdobi_od, obdobi_do, stav_upopre, platnost_od, platnost_do, ident, pozn, varsymbol, spesymbol, blokovano, id_drupre_poplatek, cislojednac, drupopre, cislopost, datvyr, nazev, cvznikradk, id_aspravce, id_aprovozna, id_najpros, obdobi_od_splt, obdobi_do_splt, kod_ctyppred, typ_predpisu, doba_platby, kod_dpla, typ_druh_platby, druh_predpisu, polonaj, anajmeno, vyp_kdatu, abyt_nebyt, za_obdobi1, za_obdobi, castkapred, castkazapl, vynospred, vynoszapl, vynosrozdil, sluzbypred, sluzbyzapl, sluzbyrozdil, dluhpred, rok, mesic, id_ccle_vlast, chyba, strp, vyppen_skut, vyppen_skut_hod, pen_predpis, ezapl_akt, penale_zakon, rokprom, nepocitat, pocet_zalob, penale_ne, datum_splatnosti, id_najvplapre, uce_doklad, datum_zaplaceni, typ_zaznamu, kod_drupre, cnajpen, kod_cnajpen, drupre_poplatek, nepoc_pen, lident_jmeno, cas_datvyr, cas_datzmeny, lident_zmena_jmeno, datzmeny, datvyr1, vynos_sluzby, zalobcislo, obdobi_od_vyu, obdobi_do_vyu, ecastka_odep, poc_zaznam, id_najvztah, id_ccle, prijmeni, jmeno, dat_nar, u_dat, prav_vznik, index_nepl, metoda_vyp, nep_od, nep_do, kod_predvzt, nazev_predvzt, kod_cisujedn, nazev_cisujedn, kod_cisustrd, nazev_cisustrd, je_isr, cnajpen_2014, typpoh, zkr_pen, spis, upominka, zapl_penale, bezduvodne_obohaceni, id_spivdatsplt, id_cnajpen, reseno) AS SELECT    MT.ID_NAJUPOMPRE ,MT.ID_NAJUPOMCEL AS ID_NAJUPOMCEL_PK,
           A9.ID_NAJUPOMCEL_A AS ID_NAJUPOMCEL,
           MT.ID_DOBAPLAT ,
           MT.ID_CTYPPRED ,MT.ID_DRUPRE ,MT.ID_POLONAJ ,
           MT.ID_DPLA ,MT.OBDOBI_OD ,MT.OBDOBI_DO,
           MT.STAV_UPOPRE,MT.PLATNOST_OD ,MT.PLATNOST_DO ,
           MT.IDENT ,MT.POZN ,MT.VARSYMBOL ,MT.SPESYMBOL ,
           MT.BLOKOVANO ,MT.ID_DRUPRE_POPLATEK,
           MT.CISLOJEDNAC ,MT.DRUPOPRE ,
           MT.CISLOPOST ,MT.DATVYR ,MT.NAZEV ,
           MT.CVZNIKRADK ,MT.ID_ASPRAVCE ,MT.ID_APROVOZNA,MT.ID_NAJPROS ,
           MT.OBDOBI_OD_SPLT ,MT.OBDOBI_DO_SPLT ,
           A3.KOD_CTYPPRED,
           A3.J1_NAZEV AS TYP_PREDPISU , A4.J1_NAZEV AS DOBA_PLATBY,
           A5.KOD_DPLA,CASE WHEN MT.ID_DPLA IS NULL THEN 'Hotovost'  ELSE A5.J1_NAZEV  END TYP_DRUH_PLATBY ,
           CASE WHEN  MT.ID_DRUPRE  IS NULL  THEN  GET_NAZEV_VYJIMKY_PEN(MT.TYP_ZAZNAMU)  ELSE  A7.J1_NAZEV   END DRUH_PREDPISU,
           A8.J1_NAZEV AS POLONAJ ,
           A9.ANAJMEN AS ANAJMENO ,
           A9.VYP_KDATU AS VYP_KDATU,
           A9A.BYT_NEBYT AS ABYT_NEBYT,
           CASE WHEN MT.za_obdobi IS NULL THEN TO_CHAR(MT.OBDOBI_OD,'MM/YYYY')  ELSE za_obdobi END ZA_OBDOBI1,
          ( FUPRAV_ZA_OBDOBI(CASE WHEN MT.za_obdobi IS NULL THEN TO_CHAR(MT.OBDOBI_OD,'MM/YYYY')  ELSE za_obdobi END )) AS ZA_OBDOBI,
           MT.CASTKAPRED , MT.CASTKAZAPL,
           MT.VYNOSPRED, MT.VYNOSZAPL, MT.VYNOSROZDIL,
           MT.SLUZBYPRED,MT.SLUZBYZAPL, MT.SLUZBYROZDIL,
           CASE WHEN  MT.NEPOCITAT = 'N'  THEN ( MT.CASTKAPRED - MT.CASTKAZAPL )   ELSE  0  END  DLUHPRED,
           MT.ROK,MT.MESIC ,
           MT.ID_CCLE_VLAST,MT.CHYBA, MT.STRP,
           ( SELECT SUM( CASE WHEN VYPPEN_SKUT IS NULL THEN 0  ELSE VYPPEN  END )
                FROM NAJPENDET B1
               WHERE B1.ID_NAJUPOMPRE = MT.ID_NAJUPOMPRE )   AS VYPPEN_SKUT,
           ( SELECT SUM( coalesce(VYPPEN_SKUT_HOD,0 ))
               FROM NAJPENDET B1
               WHERE B1.ID_NAJUPOMPRE = MT.ID_NAJUPOMPRE )   AS VYPPEN_SKUT_HOD,
           ( SELECT SUM( CASE WHEN PEN_PREDPIS IS NULL THEN 0  ELSE PEN_PREDPIS  END )
               FROM NAJPENDET B1
               WHERE B1.ID_NAJUPOMPRE = MT.ID_NAJUPOMPRE )   AS PEN_PREDPIS ,
           GET_AKTCASTKA_ZAPL_UPOMPRE( MT.ID_NAJUPOMPRE , MT.TYPPOH ) AS EZAPL_AKT,
           MT.PENALE_ZAKON ,MT.ROKPROM ,MT.NEPOCITAT ,
           MT.POCET_ZALOB ,
           CASE WHEN  MT.NEPOCITAT = 'A'  THEN  '*'   ELSE  null  END PENALE_NE,
           MT.DATUM_SPLATNOSTI  ,
           MT.ID_NAJVPLAPRE ,
           MT.UCE_DOKLAD ,
           MT.DATUM_ZAPLACENI,
           MT.TYP_ZAZNAMU,
           btrim(A7.KOD_DRUPRE) AS KOD_DRUPRE ,
           A10.J1_NAZEV AS CNAJPEN,
           A10.KOD_CNAJPEN AS KOD_CNAJPEN ,
           A11.J1_NAZEV AS DRUPRE_POPLATEK,
           MT.NEPOC_PEN,
           CASE WHEN A12.ID_SSSLOGIN IS NULL THEN MT.IDENT  ELSE A12.JMENO END LIDENT_JMENO,
           TO_CHAR(MT.DATVYR,'HH24:MI:SS') AS CAS_DATVYR,
           TO_CHAR(MT.DATZMENY,'HH24:MI:SS') AS CAS_DATZMENY,
           A13.JMENO AS LIDENT_ZMENA_JMENO ,
           MT.DATZMENY, MT.DATVYR AS DATVYR1,
           A14.VYNOS_SLUZBY,
           NAJUPOMPRE_CISLO_ZALOBY(MT.ID_NAJUPOMPRE) AS ZALOBCISLO,
           GET_OBDOBI_VYU( 'OBDOOD' , MT.ID_NAJUPOMPRE ,  'ID_NAJUPOMPRE' )
           AS OBDOBI_OD_VYU,
           GET_OBDOBI_VYU( 'OBDODO' , MT.ID_NAJUPOMPRE ,  'ID_NAJUPOMPRE' )
           AS OBDOBI_DO_VYU,
          (select
               coalesce(sum(B2.ECASTKA_ODEP),0) from najvupospl B1 ,NAJODPISY B2
               where MT.ID_NAJUPOMPRE=B1.ID_NAJUPOMPRE
               and B1.id_najdatsplt is not null
               AND B2.ID_NAJDATSPLT = B1.ID_NAJDATSPLT
           AND B2.PLATNOST_DO='01.01.4000') as ECASTKA_ODEP,
           0 as POC_ZAZNAM, A9.ID_NAJVZTAH, A15.ID_CCLE,
           A17.PRIJM AS PRIJMENI, A17.JMENO ,
           A17.DAT_NAR, A17.U_DAT,
           (case
             when MT.DATUM_SPLATNOSTI > A17.U_DAT
                 and a17.u_dat is not null and MT.datum_splatnosti is not null
             then 'Po datumu úmrtí'
             when MT.DATUM_SPLATNOSTI < A17.U_DAT
                 and a17.u_dat is not null and MT.datum_splatnosti is not null
             then 'Před datumem narození'
             else 'Po datumu splatnosti'
           end ) AS PRAV_VZNIK ,
           btrim(A14.nazev)  as INDEX_NEPL , btrim(A18.J1_NAZEV) as METODA_VYP,
           (select MIN(obdobi_od) from najupompre B1
            where B1.ID_NAJUPOMCEL=A14.ID_NAJUPOMCEL) AS NEP_OD,
           (select max(obdobi_do) from najupompre B1
            where B1.ID_NAJUPOMCEL=A14.ID_NAJUPOMCEL) AS NEP_DO,
            btrim(A20.KOD_CISPREDVZT) AS KOD_PREDVZT, btrim(A20.J1_NAZEV) AS NAZEV_PREDVZT,
            btrim(A21.KOD_CISUJEDN) AS KOD_CISUJEDN, btrim(A21.J1_NAZEV) AS NAZEV_CISUJEDN,
            btrim(A23.KOD_CISUSTRD) AS KOD_CISUSTRD, btrim(A23.J1_NAZEV) AS NAZEV_CISUSTRD,
           CASE WHEN(select count(*) from
              najvdatins B1 , najvupospl B2
              where  B1.id_najdatsplt = B2.id_najdatsplt
              and B2.id_najupompre = mt.id_najupompre )=0 THEN
            'N'  ELSE 'A' END JE_ISR,
           A24.J1_NAZEV AS CNAJPEN_2014,
         CASE WHEN  MT.TYPPOH  IS NULL  THEN (case
           when castkapred=coalesce(vynospred,0) and coalesce(vynospred,0)<>0 then 'V'
           when castkapred=coalesce(sluzbypred,0) and coalesce(sluzbypred,0)<>0 then 'S'
           else 'C'
         end )  ELSE  MT.TYPPOH  END TYPPOH,A10.ZKR_PEN,
         MT.SPIS,MT.UPOMINKA,MT.ZAPL_PENALE,MT.BEZDUVODNE_OBOHACENI,
         MT.ID_SPIVDATSPLT,MT.ID_CNAJPEN,MT.RESENO
      FROM najupompre mt
LEFT OUTER JOIN ctyppred a3 ON (MT.ID_CTYPPRED = A3.ID_CTYPPRED)
LEFT OUTER JOIN cisdopla a4 ON (MT.ID_DOBAPLAT = A4.ID_DOBAPLAT)
LEFT OUTER JOIN cisdplat a5 ON (MT.ID_DPLA = A5.ID_DPLA)
LEFT OUTER JOIN cisdrpre a7 ON (MT.ID_DRUPRE = A7.ID_DRUPRE)
LEFT OUTER JOIN cispolpre a8 ON (MT.ID_POLONAJ = A8.ID_POLONAJ)
LEFT OUTER JOIN cnajpen a10 ON (MT.ID_CNAJPEN = A10.ID_CNAJPEN)
LEFT OUTER JOIN cisdrpre a11 ON (MT.ID_DRUPRE_POPLATEK = A11.ID_DRUPRE)
LEFT OUTER JOIN ssslogin a12 ON (MT.LIDENT = A12.ID_SSSLOGIN)
LEFT OUTER JOIN ssslogin a13 ON (MT.LIDENT_ZMENA = A13.ID_SSSLOGIN)
LEFT OUTER JOIN cnajpen a24 ON (MT.ID_CNAJPEN_2014 = A24.ID_CNAJPEN)
, najupomcel a9
LEFT OUTER JOIN obpprstr a9a ON (A9.ID_PROSTOR = A9A.ID_PROSTOR)
LEFT OUTER JOIN najupomcel a14 ON (A9.ID_NAJUPOMCEL_A = A14.ID_NAJUPOMCEL)
LEFT OUTER JOIN ssshledej_a a15 ON (A9.ID_NAJVZTAH = A15.ID_NAJVZTAH)
LEFT OUTER JOIN najvztah a19 ON (A9.ID_NAJVZTAH = A19.ID_NAJVZTAH)
LEFT OUTER JOIN cisdruupo a18 ON (A14.ID_CISDRUUPO = A18.ID_CISDRUUPO)
LEFT OUTER JOIN cleosoby a16 ON (A15.ID_CCLE = A16.ID_CCLE)
LEFT OUTER JOIN parosoba a17 ON (A16.ID_OSOB = A17.ID_OSOB)
LEFT OUTER JOIN cispredvzt a20 ON (A19.ID_CISPREDVZT = A20.ID_CISPREDVZT)
LEFT OUTER JOIN cisujedn a21 ON (A19.ID_CISUJEDN = A21.ID_CISUJEDN)
LEFT OUTER JOIN ucevstrdvzt a22 ON (A19.ID_NAJVZTAH = A22.ID_NAJVZTAH)
LEFT OUTER JOIN cisustrd a23 ON (A22.ID_CISUSTRD = A23.ID_CISUSTRD)
WHERE MT.ID_NAJUPOMCEL = A9.ID_NAJUPOMCEL AND                --- REN 09.05.2016 PUVODNE A9.ID_NAJUPOMCEL(+)
        AND ( A15.TYP='N' or A15.typ is null );
</pre>

Maybe it is wrong due '---' instead '--' ?

**Comment by darold** [comment]
I will check on my regression test when I will be back to my office but here on my laptop all comments are removed and I do not have any differences between lib/Ora2Pg/PLSQL.pm and my installed file under /usr/local/share/perl/5.18.2/Ora2Pg/PLSQL.pm

**Comment by darold** [comment]
The difference comes from the action used to translate the view. Usually you might use VIEW:

    ora2pg -t VIEW -i input_file.sql

in this case, comments are removed and this why I was thinking that your installation was outdated. I think you are using action QUERY to translate the view:

     ora2pg -t QUERY -i input_file.sql

which preserve comments and reports the issue.

Even if this is not the "right" action it must works well which last commit fa68b2f has fixed.

**Comment by okbob** [comment]
I am using a VIEW type.
But this issue is not fixed still :/
<pre>
LEFT OUTER JOIN cisustrd a23 ON (A22.ID_CISUSTRD = A23.ID_CISUSTRD)                                                    
WHERE MT.ID_NAJUPOMCEL = A9.ID_NAJUPOMCEL AND                --- REN 09.05.2016 PUVODNE A9.ID_NAJUPOMCEL(+)            │
        AND ( A15.TYP='N' or A15.typ is null );   
</pre>

**Comment by darold** [comment]
Ok, translating the view from file does not have the same issue, I will try to import it from an Oracle database tomorrow.

**Comment by darold** [comment]
Please give a try to latest commit f30bf17 and let me know if that's really fix your case.

**Comment by okbob** [comment]
It is fixed, thank you

**Comment by darold** [comment]
Good news.
